plan:
    local:
        bound_min: [-2.0, -2.0, -0.5]
        bound_max: [2.0, 2.0, 0.5]
        resolution: 0.05
        safe_cost: 0.3
        safe_radius: 3
        offset_robot_p: [0.0, 0.07, -0.07]
        offset_robot_rpy: [0.0, -45.0, -90.0]
        sleep_time_ms: 50

        prob:
            map_size: [7.0, 7.0, 2.0]

        altitude:
            trun_radius: 0.4
            down_spread_dis: 2

        search:
            v_cost: 30.0
            dead_cost: 0.8
            num_limit: 20000
            z_error_thres: 10S
        
        control:
            traj_ahead_num: 5
            max_accel_add: 3.0
            max_accel_del: 12.0
            max_speed: 2.0
            speed_diff_rate: 2.39
            speed_yaw_diff_rate: 0.8
            control_interval_ms: 10
            stop_distance: 0.3
            stop_yaw: 0.15
            
    global:
        bound_min: [-10.0, -10.0, -1.0]
        bound_max: [10.0, 10.0, 1.0]
        resolution: 0.05
        safe_cost: 0.3
        safe_radius: 3
        pcd_map: "/home/ld/Documents/point_cloud/copy/lab_3_18.pcd"
        sleep_time_ms: 2000

        altitude:
            trun_radius: 0.4
            down_spread_dis: 2

        search:
            v_cost: 30.0
            dead_cost: 0.8
            num_limit: 200000


    topic_pub_odom: "/nav_core_odom"
    topic_sub_click: "/clicked_point"
    topic_pos_2d: "rm_nav_goal"
    service_nav: "/rm_nav"
    service_bot_mode: "/rm_bot_mode"
    topic_pub_local_state: "/nav_core_local_state"
    service_set_local_state: "/rm_set_l_state"

sensor:
    min_p_dis: 0.2
    topic_sub_icp: "/icp_odom"
    topic_sub_cloud: "/cloud_registered_body"
    topic_sub_odom: "/fast_lio_odom"
    FOV: [-7.0, 52.0, -180.0, 0.0]

visual:
    topic_pub_cloud_global: "/nav_core_cloud_g"
    topic_pub_cloud_local: "/nav_core_cloud_l"
    sleep_pub_cloud_global_ms: 1000
    sleep_pub_cloud_local_ms: 50
    topic_pub_safe_p:  "/nav_core_safe_p"
    topic_pub_safe_p_g: "/nav_core_safe_p_g"
    topic_pub_path_global: "/nav_core_path_g"
    topic_pub_path_local: "/nav_core_path_l"
    topic_pub_robot: "/nav_core_robot"

    region: [
        1, 2, 3,
        4, 5 ,6
    ]